# TCL File Generated by Component Editor 20.1
# Sat Jul 10 17:27:25 PDT 2021
# DO NOT MODIFY


# 
# i2s_core "I2S Core" v1.2.2
# AW 2021.07.10.17:27:25
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module i2s_core
# 
set_module_property DESCRIPTION ""
set_module_property NAME i2s_core
set_module_property VERSION 1.2.2
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Interface Protocols"
set_module_property AUTHOR AW
set_module_property DISPLAY_NAME "I2S Core"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL i2s_core
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file i2s_core.sv SYSTEM_VERILOG PATH i2s_core.sv TOP_LEVEL_FILE
add_fileset_file shiftreg_N.sv SYSTEM_VERILOG PATH shiftreg_N.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL i2s_core
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file i2s_core.sv SYSTEM_VERILOG PATH i2s_core.sv
add_fileset_file shiftreg_N.sv SYSTEM_VERILOG PATH shiftreg_N.sv


# 
# parameters
# 
add_parameter DW INTEGER 32
set_parameter_property DW DEFAULT_VALUE 32
set_parameter_property DW DISPLAY_NAME DW
set_parameter_property DW TYPE INTEGER
set_parameter_property DW UNITS None
set_parameter_property DW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DW HDL_PARAMETER true


# 
# display items
# 


# 
# connection point shiftEnable
# 
add_interface shiftEnable conduit end
set_interface_property shiftEnable associatedClock ""
set_interface_property shiftEnable associatedReset ""
set_interface_property shiftEnable ENABLED true
set_interface_property shiftEnable EXPORT_OF ""
set_interface_property shiftEnable PORT_NAME_MAP ""
set_interface_property shiftEnable CMSIS_SVD_VARIABLES ""
set_interface_property shiftEnable SVD_ADDRESS_GROUP ""

add_interface_port shiftEnable write enable Input 1


# 
# connection point sampleIn
# 
add_interface sampleIn conduit end
set_interface_property sampleIn associatedClock ""
set_interface_property sampleIn associatedReset ""
set_interface_property sampleIn ENABLED true
set_interface_property sampleIn EXPORT_OF ""
set_interface_property sampleIn PORT_NAME_MAP ""
set_interface_property sampleIn CMSIS_SVD_VARIABLES ""
set_interface_property sampleIn SVD_ADDRESS_GROUP ""

add_interface_port sampleIn writedata data Input 32


# 
# connection point bitOut
# 
add_interface bitOut conduit end
set_interface_property bitOut associatedClock ""
set_interface_property bitOut associatedReset ""
set_interface_property bitOut ENABLED true
set_interface_property bitOut EXPORT_OF ""
set_interface_property bitOut PORT_NAME_MAP ""
set_interface_property bitOut CMSIS_SVD_VARIABLES ""
set_interface_property bitOut SVD_ADDRESS_GROUP ""

add_interface_port bitOut streamout data Output 1


# 
# connection point SCLK
# 
add_interface SCLK conduit end
set_interface_property SCLK associatedClock ""
set_interface_property SCLK associatedReset ""
set_interface_property SCLK ENABLED true
set_interface_property SCLK EXPORT_OF ""
set_interface_property SCLK PORT_NAME_MAP ""
set_interface_property SCLK CMSIS_SVD_VARIABLES ""
set_interface_property SCLK SVD_ADDRESS_GROUP ""

add_interface_port SCLK SCLK clk Input 1


# 
# connection point LRCLK
# 
add_interface LRCLK conduit end
set_interface_property LRCLK associatedClock ""
set_interface_property LRCLK associatedReset ""
set_interface_property LRCLK ENABLED true
set_interface_property LRCLK EXPORT_OF ""
set_interface_property LRCLK PORT_NAME_MAP ""
set_interface_property LRCLK CMSIS_SVD_VARIABLES ""
set_interface_property LRCLK SVD_ADDRESS_GROUP ""

add_interface_port LRCLK LRCLK clk Input 1


# 
# connection point Reset
# 
add_interface Reset conduit end
set_interface_property Reset associatedClock ""
set_interface_property Reset associatedReset ""
set_interface_property Reset ENABLED true
set_interface_property Reset EXPORT_OF ""
set_interface_property Reset PORT_NAME_MAP ""
set_interface_property Reset CMSIS_SVD_VARIABLES ""
set_interface_property Reset SVD_ADDRESS_GROUP ""

add_interface_port Reset Reset reset Input 1

